name: pop

services:

  api:
    container_name: api
    image: centreonlabs/pop
    ports:
      - 8000:8000
    environment:
      - POP_CONFIG_PATH=${POP_CONFIG_PATH:-/root/.pop/config.yaml}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - pop:/root/.pop
      - type: bind
        source: docker/entrypoint_api.sh
        target: /root/.pop/entrypoint.sh
    networks:
      - pop
    entrypoint: ["/root/.pop/entrypoint.sh"]
    command: [ "uvicorn", "--host", "0.0.0.0", "--port", "8000", "--log-config", "log_conf.yaml", "plugin_output_processing.api:app" ]
    
  ollama:
    container_name: ollama
    image: ollama/ollama
    profiles:
      - ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - pop

volumes:
  pop:
  ollama:

networks:
  pop:
