name: pop

services:

  api:
    container_name: api
    image: centreonlabs/pop
    ports:
      - 8000:8000
    environment:
      - POP_CONFIG_PATH=${POP_CONFIG_PATH:-/root/.pop/config.yaml}
      - OLLAMA_HOST=${OLLAMA_HOST:-ollama}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - pop:/root/.pop
    networks:
      - pop
    
  ollama:
    container_name: ollama
    image: ollama/ollama
    profiles:
      - ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - pop

volumes:
  pop:
  ollama:

networks:
  pop:
