

services:

  pop:
    container_name: api
    image: centreonlabs/pop
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POP_CONFIG_PATH=/root/.pop/config.yaml
      - OLLAMA_HOST=ollama
    volumes:
      - pop:/root/.pop
    networks:
      - pop
    depends_on:
      init-ollama:
        condition: service_completed_successfully

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - pop
    healthcheck:
      test: "ollama"
      interval: 2s
      timeout: 5s
      retries: 5
  
  init-ollama:
    container_name: init-ollama
    image: alpine/curl:latest
    command: curl -s -X POST http://ollama:11434/api/pull -d {\"name\":\"qwen2:0.5b\"}
    networks:
      - pop
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  pop:
  ollama:


networks:
  pop: