name: pop

services:

  api:
    container_name: api
    image: centreonlabs/pop:${POP_VERSION:-latest}
    ports:
      - 8000:8000
    environment:
      - POP_CONFIG_PATH=/root/config/pop.yaml
      - POP_OLLAMA_DEFAULT_MODEL=${POP_OLLAMA_DEFAULT_MODEL:-qwen2:0.5b}
      - OLLAMA_HOST=ollama
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - config:/root/config
    networks:
      - pop
    
  ollama:
    container_name: ollama
    image: ollama/ollama
    profiles:
      - ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - pop

volumes:
  config:
  ollama:

networks:
  pop:
